global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: node
    static_configs:
    - targets:
      - localhost:9100

  - job_name: gpu
    static_configs:
    - targets:
      - localhost:9835
