name: Build GPU-Managet Images
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  ubuntu-2204:
    name: Build Custom Image Ubuntu 22.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Ubuntu-22.04/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:ubuntu-22.04

  pytorch-2.1.2_cuda-12.1_python-3.10_ubuntu-22.04:
    name: Build Custom Image PyTorch 1.10.0 CUDA 11.4 Python 3.9 Ubuntu 22.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Pytorch-2.1.2_Cuda-12.1_Python-3.10_Ubuntu-22.04/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gpu-manager:pytorch-2.1.2_cuda-12.1_python-3.10_ubuntu-22.04